name: Create GitLab Issue

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Title of the issue"
        required: true
      description:
        description: "Description of the issue"
        required: true

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitLab Issue
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
          GITLAB_URL: ${{ secrets.GITLAB_URL }}
        run: |
          curl -k --request POST \
          --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
          --header "Content-Type: application/json" \
          --data '{
            "title": "${{ github.event.inputs.title }}",
            "description": "${{ github.event.inputs.description }}"
          }' \
          "$GITLAB_URL/api/v4/projects/$GITLAB_PROJECT_ID/issues"
